### PR TITLE
Added quick new LED pattern Sparkle!

### PR DESCRIPTION
**Pull request by Pysis868**
Adding this to work out the process, before we get into the advanced stuff.

Didn't unit or integration test.  Let's add some unit tests later so we don't need to push the code everytime and have the badge handy?

Added guide for adding new LED patterns to the README.

Sorry about the whitespaces edits... For the better??

### CODE REVIEW

**Review by melvin2001 — COMMENTED** [review]
Looks good, I'll wait for Doug for final approval unless someone else wants to peer.

**Comment by pandatrax** [comment]
Nice! Thanks!

**Comment by pandatrax** [comment]
Had to add to the patternTimes and patternLengths arrays. Also had to change the if in changePattern() to "if (tmpPattern < **8**) {".

There are probably better ways to do these things.

**Comment by Pysis868** [comment]
Cool!

Already had the config file idea, when-/who-ever gets to it :)
https://en.wikipedia.org/wiki/Data-driven_programming

Which lead to thinking the embedded chip having limited storage, we would probably want to store the single active pattern to display, rather than all of them and the choice integer pointer.

**Comment by melvin2001** [comment]
https://learn.adafruit.com/memories-of-an-arduino/you-know-you-have-a-memory-problem-when-dot-dot-dot

is a great resource to optimizing arduino memory usage.

**Pull request merged**
